from flask import Flask, request, jsonify, render_template
from fuzzywuzzy import process

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/get_response', methods=['POST'])
def get_response():
    user_input = request.form['user_input']
    response = ""

    # Check user input for help
    if user_input.lower() == 'help':
        response = "You can choose from the following options:<br>"
        response += "1. Search on <a href='https://www.google.com'>Google</a><br>"
        response += "2. Watch videos on <a href='https://www.youtube.com'>YouTube</a>"
    else:
        # Sample training data
        training_data = {
            "who is your college principle":"Honorable Mr. Makrand Wazal Sir",
            "who is your master":"My Master is Yash and Pratik",
            "hi": "Hello! How can I assist you?",
    "hello": "Hi there! How can I help you today?",
    "how are you?": "I'm just a bot, but I'm here to help you!",
    "what can you do?": "I can assist you with various tasks like searching on Google or watching YouTube videos.",
    "thank you": "You're welcome!",
    "bye": "Goodbye! Feel free to return if you have more questions.",
    "what's your name?": "I'm a chatbot designed to assist you. You can call me ChatBot.",
    "who created you?": "I was created by [yash and pratik].",
    "where are you located?": "I exist in the digital realm, accessible wherever you have an internet connection.",
    "do you have feelings?": "I don't have feelings, but I'm here to provide you with assistance and information.",
    "can you tell a joke?": "Why don't skeletons fight each other? They don't have the guts!",
    "how old are you?": "I don't have an age in the way humans do. I exist to assist you.",
    "tell me a fact": "Did you know that the Earth's atmosphere is composed of approximately 78% nitrogen, 21% oxygen, and 1% other gases?",
    "can you help me with math?": "Certainly! Please provide me with the math problem you need help with.",
    "what's the weather like?": "I'm sorry, I don't have access to real-time weather data. You can check a weather website or app for that information.",
    "can you sing a song?": "I'm better at providing information than singing, but I can look up song lyrics for you!",
    "are you human?": "No, I'm a chatbot programmed to assist you with your inquiries.",
    "what languages do you speak?": "I primarily speak the language of the users interacting with me, but I can understand and respond in multiple languages.",
    "can you recommend a movie?": "Sure! What genre of movie are you interested in?",
    "what's your favorite color?": "I don't have personal preferences like humans do, but I can appreciate all colors!",
    "how do I contact support?": "You can contact support through our website or by emailing [Support Email].",
    "tell me about yourself": "I am an AI chatbot designed to assist you with your queries. Feel free to ask me anything!",
    "what time is it?": "I'm sorry, I don't have access to the current time.",
    "can you help me find a restaurant?": "Sure! What type of cuisine are you interested in?",
    "how can I improve my productivity?": "There are many ways to improve productivity, such as setting goals, prioritizing tasks, and minimizing distractions.",
    "tell me a story": "Once upon a time, in a faraway land...",
    "what's the meaning of life?": "The meaning of life is a question that has puzzled humans for centuries. It's up to each individual to find their own meaning and purpose.",
    "can you help me with my homework?": "I can try! Please provide the details of your homework assignment.",
    "what's the capital of France?": "The capital of France is Paris.",
    "how do I change my password?": "You can change your password in the settings section of your account.",
    "can you help me plan a trip?": "Of course! Where would you like to go?",
    "what's the largest planet in the solar system?": "Jupiter is the largest planet in our solar system.",
    "can you translate this phrase for me?": "Sure! Please provide the phrase and the language you'd like it translated to.",
    "what's your favorite food?": "I don't eat, but I'm here to help you find your favorite foods!",
    "can you recommend a book?": "Sure! What genre of book are you interested in?",
    "what's the square root of 144?": "The square root of 144 is 12.",
    "can you help me troubleshoot my computer?": "I can provide some general troubleshooting tips. What seems to be the problem?",
    "what's the population of China?": "As of the latest estimates, the population of China is over 1.4 billion people.",
    "how can I learn programming?": "There are many online resources and tutorials available to help you learn programming. It's important to start with the basics and practice regularly.",
"what's the diameter of the Earth?": "The diameter of the Earth is approximately 12,742 kilometers.",
    "can you help me with my resume?": "Certainly! I can provide tips and guidelines for creating a professional resume.",
    "what's the difference between weather and climate?": "Weather refers to short-term atmospheric conditions in a specific place, while climate refers to long-term patterns of temperature, precipitation, and other factors.",
    "how can I stay motivated?": "Staying motivated can be challenging, but setting achievable goals, staying organized, and finding inspiration can help.",
    "can you help me with public speaking?": "Sure! I can offer tips on preparing and delivering effective speeches.",
    "what's the Pythagorean theorem?": "The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse (the side opposite the right angle) is equal to the sum of the squares of the lengths of the other two sides.",
    "what's the speed of light?": "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "how do I create a budget?": "Creating a budget involves tracking your income and expenses, setting financial goals, and prioritizing spending.",
    "can you help me find a job?": "Certainly! I can provide tips on writing resumes, preparing for interviews, and searching for job openings.",
    "what's the capital of Japan?": "The capital of Japan is Tokyo.",
    "how does the internet work?": "The internet is a global network of interconnected computers that communicate using standardized protocols.",
    "can you recommend a podcast?": "Sure! What topics are you interested in?",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start investing?": "Investing involves purchasing assets with the expectation of generating income or profit over time. It's important to research and understand different investment options before getting started.",
    "what's the population of India?": "As of the latest estimates, the population of India is over 1.3 billion people.",
    "how do I cook pasta?": "To cook pasta, bring a pot of water to a boil, add salt, and then add the pasta. Cook until it's al dente, then drain and serve with your favorite sauce.",
    "can you recommend a workout routine?": "Sure! What are your fitness goals?",
    "what's the difference between a virus and a bacterium?": "Viruses are infectious agents that require a host cell to replicate, while bacteria are single-celled microorganisms that can live independently.",
    "how can I improve my memory?": "Practicing good sleep habits, staying mentally active, and using mnemonic devices can help improve memory.",
    "can you help me understand quantum mechanics?": "Quantum mechanics is a branch of physics that describes the behavior of particles at the smallest scales, such as atoms and subatomic particles.",
    "what's the longest river in the world?": "The longest river in the world is the Nile River in Africa.",
    "how do I start a small business?": "Starting a small business involves creating a business plan, securing financing, and registering your business with the appropriate authorities.",
    "can you recommend a documentary?": "Sure! What topics interest you?",
    "what's the difference between Celsius and Fahrenheit?": "Celsius and Fahrenheit are two different temperature scales. Celsius is based on the freezing and boiling points of water, while Fahrenheit is based on a scale devised by Daniel Gabriel Fahrenheit.",
    "how do I start meditating?": "To start meditating, find a quiet and comfortable space, sit or lie down in a relaxed position, and focus on your breath or a mantra.",
    "can you help me learn a new language?": "Learning a new language takes practice and dedication. Immersing yourself in the language, practicing regularly, and using language-learning resources can help.",
    "what's the tallest mountain in the world?": "Mount Everest, located in the Himalayas, is the tallest mountain in the world.",
    "how do I build a website?": "Building a website involves choosing a domain name, selecting a web hosting provider, and designing and coding your site using HTML, CSS, and other web technologies.",
    "can you recommend a video game?": "Sure! What genre of video game do you enjoy?",
    "what's the difference between a fruit and a vegetable?": "Botanically, fruits develop from the ovary of a flowering plant and contain seeds, while vegetables are other edible parts of plants, such as roots, stems, and leaves.",
    "how do I start a blog?": "To start a blog, choose a blogging platform, select a domain name, design your blog, and start creating and publishing content.",
    "can you help me write a poem?": "Of course! What theme or topic would you like the poem to explore?",
    "what's the difference between a credit card and a debit card?": "A credit card allows you to borrow money up to a certain limit, while a debit card deducts funds directly from your checking account.",
    "how do I make a good first impression?": "Making a good first impression involves being punctual, dressing appropriately, and displaying confidence and positivity.",
    "can you recommend a board game?": "Sure! Are you looking for a strategy game, a party game, or something else?",
    "what's the difference between a democracy and a republic?": "In a democracy, decisions are made by the majority of the people, while in a republic, the people elect representatives to make decisions on their behalf.",
    "how do I write a book?": "Writing a book involves planning your story, creating memorable characters, and dedicating time to writing and revising.",
    "can you help me overcome procrastination?": "Certainly! Setting clear goals, breaking tasks into smaller steps, and eliminating distractions can help overcome procrastination.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start investing in the stock market?": "To start investing in the stock market, research different investment options, open a brokerage account, and consider diversifying your portfolio.",
    "what's the difference between weather and climate?": "Weather refers to short-term atmospheric conditions in a specific place, while climate refers to long-term patterns of temperature, precipitation, and other factors.",
    "can you help me improve my public speaking skills?": "Sure! Practice speaking in front of a mirror, join a public speaking club, and study great speeches for inspiration.",
    "what's the difference between a CV and a resume?": "A CV (curriculum vitae) is a comprehensive document that provides an overview of a person's academic and professional history, while a resume is a brief summary of a person's skills and experience tailored to a specific job.",
    "how do I start a podcast?": "To start a podcast, choose a topic, select recording equipment, record and edit your episodes, and publish them on podcast platforms.",
    "can you recommend a good book on leadership?": "Sure! 'Leaders Eat Last' by Simon Sinek is a highly recommended book on leadership.",
    "what's the difference between a galaxy and a solar system?": "A galaxy is a massive collection of stars, gas, dust, and dark matter bound together by gravity, while a solar system consists of a star and all the objects that orbit it, including planets, moons, asteroids, and comets.",
    "how do I create a strong password?": "To create a strong password, use a combination of letters, numbers, and special characters, and avoid using easily guessable information like your name or birthdate.",
    "can you recommend a good movie for a date night?": "Sure! Romantic comedies like 'When Harry Met Sally' or 'The Notebook' are popular choices for date nights.",
    "what's the difference between a mammal and a reptile?": "Mammals are warm-blooded animals that typically have fur or hair and give birth to live young, while reptiles are cold-blooded animals that lay eggs and have scales or scaly skin.",
    "how do I become more confident?": "Building confidence takes practice and self-awareness. Set achievable goals, celebrate your successes, and practice positive self-talk.",
    "can you recommend a good documentary on nature?": "Sure! 'Planet Earth' and 'Our Planet' are excellent documentary series that showcase the beauty and diversity of nature.",
    "what's the difference between a PhD and a master's degree?": "A PhD (Doctor of Philosophy) is a terminal degree that typically involves original research and the completion of a dissertation, while a master's degree is a graduate degree that usually requires coursework and may involve a thesis or capstone project.",
    "how do I start a YouTube channel?": "To start a YouTube channel, choose a niche, create high-quality content, optimize your videos for search, and engage with your audience.",
    "can you help me learn to play the guitar?": "Sure! Start by learning basic chords and practicing regularly. There are also many online resources and tutorials available to help you learn.",
    "what's the difference between a metaphor and a simile?": "A metaphor is a figure of speech that directly compares two unrelated things, while a simile compares two things using 'like' or 'as'.",
    "how do I start a nonprofit organization?": "To start a nonprofit organization, define your mission, recruit a board of directors, file the necessary paperwork, and obtain tax-exempt status.",
    "can you recommend a good TV series to binge-watch?": "Sure! 'Breaking Bad,' 'Game of Thrones,' and 'Stranger Things' are popular choices for binge-watching.",
    "what's the difference between an herb and a spice?": "Herbs come from the leaves of plants, while spices come from other parts of plants, such as seeds, bark, or roots.",
    "how do I start a career in graphic design?": "To start a career in graphic design, develop your skills with design software, build a portfolio, and consider internships or freelance projects to gain experience.",
    "can you help me write a cover letter?": "Certainly! A cover letter should introduce yourself, highlight your qualifications, and explain why you're interested in the position.",
    "what's the difference between a memoir and an autobiography?": "A memoir focuses on a specific period or theme in a person's life, while an autobiography covers the person's entire life from birth to the present.",
    "how do I start a career in photography?": "To start a career in photography, invest in quality equipment, develop your skills through practice and study, and build a strong portfolio.",
    "can you recommend a good podcast for learning about history?": "Sure! 'Hardcore History' and 'Stuff You Missed in History Class' are excellent podcasts for learning about history.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in filmmaking?": "To start a career in filmmaking, learn the fundamentals of storytelling and filmmaking techniques, create short films to showcase your skills, and network with others in the industry.",
    "can you recommend a good book for personal development?": "Sure! 'The 7 Habits of Highly Effective People' by Stephen Covey is a classic book for personal development.",
    "what's the difference between a recession and a depression?": "A recession is a period of economic decline characterized by a decrease in GDP and rising unemployment, while a depression is a more severe and prolonged economic downturn.",
    "how do I start a career in writing?": "To start a career in writing, practice writing regularly, read widely in different genres, and consider taking writing workshops or courses to improve your skills.",
    "can you recommend a good book for learning about psychology?": "Sure! 'Thinking, Fast and Slow' by Daniel Kahneman is a fascinating book that explores the psychology of decision-making.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in marketing?": "To start a career in marketing, gain experience through internships or entry-level positions, develop skills in areas like digital marketing and analytics, and stay updated on industry trends.",
    "can you recommend a good book for learning about economics?": "Sure! 'Freakonomics' by Steven Levitt and Stephen Dubner is an engaging book that applies economic principles to everyday phenomena.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in healthcare?": "To start a career in healthcare, explore different healthcare professions, pursue relevant education and training, and gain experience through internships or volunteer work.",
    "can you recommend a good book for learning about philosophy?": "Sure! 'Sophie's World' by Jostein Gaarder is an accessible introduction to the history of philosophy.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in technology?": "To start a career in technology, gain technical skills through education and training, build a portfolio of projects, and stay updated on emerging technologies.",
    "can you recommend a good book for learning about science?": "Sure! 'A Brief History of Time' by Stephen Hawking is a popular book that explores complex scientific concepts in a accessible way.",
    "what's the difference between a hypothesis and a theory?": "A hypothesis is a proposed explanation for a phenomenon, while a theory is a well-substantiated explanation based on evidence and experimentation.",
    "how do I start a career in cybersecurity?": "To start a career in cybersecurity, gain expertise in areas such as network security, cryptography, and ethical hacking, and obtain relevant certifications.",
    "can you recommend a good book for learning about artificial intelligence?": "Sure! 'Artificial Intelligence: A Modern Approach' by Stuart Russell and Peter Norvig is a comprehensive introduction to AI.",
    "what's the difference between a novel and a short story?": "A novel is a long work of fiction typically containing multiple characters and plotlines, while a short story is a brief narrative focused on a single event or character.",
    "how do I improve my writing skills?": "To improve your writing skills, practice regularly, seek feedback from others, and study the works of accomplished writers.",
    "can you recommend a good movie for a family night?": "Sure! Animated films like 'Toy Story' or 'Finding Nemo' are great choices for family movie nights.",
    "what's the difference between a vegetarian and a vegan?": "A vegetarian abstains from eating meat, while a vegan avoids all animal products, including meat, dairy, and eggs.",
    "how do I start a career in data science?": "To start a career in data science, learn programming languages like Python and R, acquire knowledge of statistics and machine learning, and work on real-world projects.",
    "can you recommend a good book for learning about mindfulness?": "Sure! 'The Miracle of Mindfulness' by Thich Nhat Hanh is a classic book on mindfulness meditation.",
    "what's the difference between gross income and net income?": "Gross income is the total earnings before deductions, while net income is the amount remaining after subtracting expenses and deductions.",
    "how do I start a career in environmental conservation?": "To start a career in environmental conservation, gain knowledge in areas such as ecology and conservation biology, participate in volunteer projects, and pursue internships or degrees in related fields.",
    "can you recommend a good movie for a date night?": "Sure! Romantic comedies like 'When Harry Met Sally' or 'The Notebook' are popular choices for date nights.",
    "what's the difference between a CV and a resume?": "A CV (curriculum vitae) is a comprehensive document that provides an overview of a person's academic and professional history, while a resume is a brief summary of a person's skills and experience tailored to a specific job.",
    "how do I start a career in web development?": "To start a career in web development, learn programming languages such as HTML, CSS, and JavaScript, build projects to showcase your skills, and consider pursuing formal education or certifications.",
    "can you recommend a good book for learning about psychology?": "Sure! 'Thinking, Fast and Slow' by Daniel Kahneman is a fascinating book that explores the psychology of decision-making.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in marketing?": "To start a career in marketing, gain experience through internships or entry-level positions, develop skills in areas like digital marketing and analytics, and stay updated on industry trends.",
    "can you recommend a good book for learning about economics?": "Sure! 'Freakonomics' by Steven Levitt and Stephen Dubner is an engaging book that applies economic principles to everyday phenomena.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in technology?": "To start a career in technology, gain technical skills through education and training, build a portfolio of projects, and stay updated on emerging technologies.",
    "can you recommend a good book for learning about science?": "Sure! 'A Brief History of Time' by Stephen Hawking is a popular book that explores complex scientific concepts in a accessible way.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "how do I start a career in healthcare?": "To start a career in healthcare, explore different healthcare professions, pursue relevant education and training, and gain experience through internships or volunteer work.",
    "can you recommend a good book for learning about philosophy?": "Sure! 'Sophie's World' by Jostein Gaarder is an accessible introduction to the history of philosophy.",
    "what's the difference between empathy and sympathy?": "Empathy involves understanding and sharing the feelings of others, while sympathy involves feeling compassion or sorrow for someone else's situation.",
    "what's the meaning of courage?": "Courage is the mental or moral strength to persevere and withstand danger, fear, or difficulty.",
    "what's the meaning of resilience?": "Resilience is the capacity to recover quickly from difficulties or setbacks, often with increased strength or adaptability.",
    "what's the meaning of perseverance?": "Perseverance is the persistence in doing something despite obstacles, challenges, or setbacks.",
    "what's the meaning of integrity?": "Integrity is the quality of being honest, ethical, and upright in one's actions and character.",
    "what's the meaning of gratitude?": "Gratitude is the feeling of appreciation or thankfulness towards someone or something.",
    "what's the meaning of mindfulness?": "Mindfulness is the practice of being present and fully engaged in the current moment, without judgment or distraction.",
    "what's the meaning of success?": "Success is the achievement of a goal or objective, often accompanied by recognition, satisfaction, or fulfillment.",
    "what's the meaning of failure?": "Failure is the lack of success in achieving a desired goal or outcome, often accompanied by disappointment or setback.",
    "what's the meaning of happiness?": "Happiness is a positive emotional state characterized by feelings of contentment, joy, and fulfillment.",
    "what's the meaning of sadness?": "Sadness is a negative emotional state characterized by feelings of sorrow, grief, or melancholy.",
    "what's the meaning of anger?": "Anger is a strong feeling of displeasure or hostility towards someone or something, often accompanied by a desire to retaliate or confront the source of frustration.",
    "what's the meaning of fear?": "Fear is an emotional response to perceived threats or dangers, often characterized by feelings of anxiety, apprehension, or dread.",
    "what's the meaning of love?": "Love is a complex and deeply personal emotion that can mean different things to different people.",
    "what's the meaning of trust?": "Trust is the belief in the reliability, truth, or ability of someone or something, often accompanied by a willingness to rely on or confide in them.",
    "what's the meaning of respect?": "Respect is the regard and admiration for someone or something, often accompanied by consideration, courtesy, or deference.",
    "what's the meaning of loyalty?": "Loyalty is the faithfulness, allegiance, or devotion to someone or something, often accompanied by a sense of duty or obligation.",
    "what's the meaning of responsibility?": "Responsibility is the obligation or accountability for one's actions, decisions, or duties, often accompanied by a commitment to fulfill them conscientiously.",
    "what's the meaning of freedom?": "Freedom is the state of being free from constraints, limitations, or restrictions, often accompanied by the ability to make choices and pursue one's interests.",
    "what's the meaning of justice?": "Justice is the fairness, impartiality, or equity in the treatment of individuals or the resolution of disputes, often accompanied by adherence to legal or moral principles.",
    "what's the meaning of equality?": "Equality is the state of being equal in rights, opportunities, or status, often accompanied by the absence of discrimination or prejudice.",
    "what's the meaning of diversity?": "Diversity is the presence of a variety of different cultures, perspectives, or identities within a group, organization, or community.",
    "what's the meaning of inclusion?": "Inclusion is the practice of creating environments or policies that embrace and support the participation and contribution of individuals from diverse backgrounds or identities.",
    "what's the meaning of sustainability?": "Sustainability is the ability to meet the needs of the present without compromising the ability of future generations to meet their own needs, often accompanied by practices that conserve resources and protect the environment.",
    "what's the meaning of innovation?": "Innovation is the process of introducing new ideas, methods, or products that create value or address challenges, often accompanied by creativity, experimentation, or risk-taking.",
    "what's the meaning of collaboration?": "Collaboration is the act of working together with others to achieve a common goal or objective, often accompanied by communication, cooperation, or shared resources.",
    "what's the meaning of teamwork?": "Teamwork is the combined effort of individuals working together cooperatively and effectively to accomplish shared goals or tasks, often accompanied by mutual support, trust, and accountability.",
    "what's the meaning of leadership?": "Leadership is the ability to inspire, motivate, and guide others towards a shared vision or goal, often accompanied by influence, decision-making, and accountability.",
    "what's the meaning of communication?": "Communication is the exchange of information, ideas, or feelings between individuals or groups through verbal or nonverbal means, often accompanied by listening, understanding, and feedback.",
    "what's the meaning of empathy?": "Empathy is the ability to understand and share the feelings of others, often accompanied by the desire to help or support them.",
    "what's the meaning of creativity?": "Creativity is the ability to generate original ideas, solutions, or expressions that are novel, useful, or meaningful, often accompanied by imagination, exploration, or experimentation.",
    "what's the meaning of critical thinking?": "Critical thinking is the process of analyzing, evaluating, or synthesizing information and arguments in a logical and systematic manner to make reasoned judgments or decisions.",
    "what's the meaning of problem-solving?": "Problem-solving is the process of identifying, analyzing, and resolving problems or challenges in a systematic and effective manner, often accompanied by creativity, logic, or collaboration.",
    "what's the meaning of resilience?": "Resilience is the capacity to recover quickly from difficulties or setbacks, often with increased strength or adaptability.",
    "what's the meaning of perseverance?": "Perseverance is the persistence in doing something despite obstacles, challenges, or setbacks.",
    "what's the meaning of integrity?": "Integrity is the quality of being honest, ethical, and upright in one's actions and character.",
    "what's the meaning of gratitude?": "Gratitude is the feeling of appreciation or thankfulness towards someone or something.",
    "what's the meaning of mindfulness?": "Mindfulness is the practice of being present and fully engaged in the current moment, without judgment or distraction.",
    "what's the meaning of collaboration?": "Collaboration is the act of working together with others to achieve a common goal or objective, often accompanied by communication, cooperation, or shared resources.",
    "what's the meaning of teamwork?": "Teamwork is the combined effort of individuals working together cooperatively and effectively to accomplish shared goals or tasks, often accompanied by mutual support, trust, and accountability.",
    "what's the meaning of leadership?": "Leadership is the ability to inspire, motivate, and guide others towards a shared vision or goal, often accompanied by influence, decision-making, and accountability.",
    "what's the meaning of communication?": "Communication is the exchange of information, ideas, or feelings between individuals or groups through verbal or nonverbal means, often accompanied by listening, understanding, and feedback.",
    "what's the meaning of empathy?": "Empathy is the ability to understand and share the feelings of others, often accompanied by the desire to help or support them.",
    "what's the meaning of creativity?": "Creativity is the ability to generate original ideas, solutions, or expressions that are novel, useful, or meaningful, often accompanied by imagination, exploration, or experimentation.",
    "what's the meaning of critical thinking?": "Critical thinking is the process of analyzing, evaluating, or synthesizing information and arguments in a logical and systematic manner to make reasoned judgments or decisions.",
    "what's the meaning of problem-solving?": "Problem-solving is the process of identifying, analyzing, and resolving problems or challenges in a systematic and effective manner, often accompanied by creativity, logic, or collaboration.",
    "what's the meaning of resilience?": "Resilience is the capacity to recover quickly from difficulties or setbacks, often with increased strength or adaptability.",
    "what's the meaning of perseverance?": "Perseverance is the persistence in doing something despite obstacles, challenges, or setbacks.",
    "what's the meaning of integrity?": "Integrity is the quality of being honest, ethical, and upright in one's actions and character.",
    "what's the meaning of gratitude?": "Gratitude is the feeling of appreciation or thankfulness towards someone or something.",
    "what's the meaning of mindfulness?": "Mindfulness is the practice of being present and fully engaged in the current moment, without judgment or distraction.",
        }

        # Fuzzy matching
        matched_question, score = process.extractOne(user_input.lower(), training_data.keys())

        # If the score is above a certain threshold, treat it as a match
        if score >= 70:
            response = training_data[matched_question]
        else:
            response = "I'm sorry, I didn't understand that."

    return jsonify({'response': response})

if __name__ == '__main__':
    app.run(debug=True)
